name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14" # Set this to your project's required Node.js version
      - run: npm install
      - run: npm run build
        env:
          CI: false
        continue-on-error: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication.

